// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlannerAgent.Infrastructure.Persistence.EfCore;

#nullable disable

namespace StudyPlannerAgent.Infrastructure.Persistence.EfCore.Migrations
{
    [DbContext(typeof(StudyPlannerDbContext))]
    [Migration("20260812183919_AddUniqueStudyTopicSchedule")]
    partial class AddUniqueStudyTopicSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyProgressEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer")
                        .HasColumnName("percentage");

                    b.Property<DateOnly>("StudiedOn")
                        .HasColumnType("date")
                        .HasColumnName("studied_on");

                    b.Property<Guid>("StudyTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_topic_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyTopicId");

                    b.HasIndex("UserId");

                    b.ToTable("study_progress_entries", (string)null);
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyScheduleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("StudyTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_topic_id");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer")
                        .HasColumnName("weekday");

                    b.HasKey("Id");

                    b.HasIndex("StudyTopicId")
                        .IsUnique();

                    b.ToTable("study_schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Weekday = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Weekday = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Weekday = 3
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Weekday = 4
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Weekday = 5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            Weekday = 6
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7"),
                            StudyTopicId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            Weekday = 0
                        });
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyTopicRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("study_topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Review syntax, records, LINQ and async/await.",
                            Name = "C# fundamentals"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Practice controllers, minimal APIs, dependency injection and middleware.",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Description = "Review domain, application, infrastructure and API boundaries.",
                            Name = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Practice tables, EF Core mappings and repository adapters.",
                            Name = "Supabase/Postgres"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Description = "Study tools, MCP server transport and agent integration.",
                            Name = "MCP and Foundry"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            Description = "Build small features and write notes about tradeoffs.",
                            Name = "Project practice"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            Description = "Review progress, gaps and next week focus.",
                            Name = "Weekly review"
                        });
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyProgressEntryRecord", b =>
                {
                    b.HasOne("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyTopicRecord", "StudyTopic")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("StudyTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.UserRecord", "User")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyScheduleRecord", b =>
                {
                    b.HasOne("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyTopicRecord", "StudyTopic")
                        .WithMany("Schedules")
                        .HasForeignKey("StudyTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyTopic");
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.StudyTopicRecord", b =>
                {
                    b.Navigation("ProgressEntries");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("StudyPlannerAgent.Infrastructure.Persistence.EfCore.Records.UserRecord", b =>
                {
                    b.Navigation("ProgressEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
